### PR TITLE
Fix invalid map indexers order

### LINKED ISSUE #10: Fix map indexers
At the moment x and y of map are bound to array like this:
`map[layer][x][y]`

But the actual map should be indexed that way:
`map[layer][y][x]`
because in 2-dimensional arrays y (row) is first indexer.

### PR DESCRIPTION
**Pull request by F1uctus**
Fixes #10

### CODE REVIEW

File: src/main/java/rpgram/RPGram.java [hunk 1]
```diff
@@ -136,9 +136,9 @@ public void onUpdateReceived(Update update) {
             }
             case "map":
             case "back": {
-                answer = curPlayer.getMap().viewMapArea(curPlayer.getPos(), curPlayer.getFov());
+                String mapArea = curPlayer.getMap().viewMapArea(curPlayer.getPos(), curPlayer.getFov());
```
Comment (artyom-poptsov) [inline src/main/java/rpgram/RPGram.java]: This line is too long.  I suggest to make it shorter.  For example:
```suggestion
                String mapArea = curPlayer.getMap().viewMapArea(
                        curPlayer.getPos(),
                        curPlayer.getFov()
                );
```
